### PR TITLE
Add Dockerfile for ubuntu:latest

### PR DESCRIPTION
**Pull request by cissieAB**
## Updates
- [x] Add a Dockerfile for ubuntu:latest, which has JANA, ersap-cpp, ersap-java and xmsg-cpp env containerized.
- [x] Add /build to .gitignore

### Build and install ersap-jana
Built successfully. After `make install`,
```
root@6d6a0ecc97a6:/app/build# ls $ERSAP_HOME/plugins/jana/
lib  services
```
### Run ersap-shell
Do not know whether its expected or not.
```
ersap> set servicesFile /app/services.yaml 

ersap> run local
tee: /usr/local/ersap/plugins/epsci/log/10.0.2.100_root_ersap_fe_dpe.log: No such file or directory

==========================================
               ERSAP FE/DPE               
==========================================
 Name             = 10.0.2.100%7120_java
 Session          = root_ersap
 Start time       = 2023-01-28 02:40:50
 Version          = 1.0
 Lang             = Java
 Pool size        = 8

 Proxy Host       = 10.0.2.100
 Proxy Port       = 7120
==========================================
tee: /usr/local/ersap/plugins/epsci/log/10.0.2.100_root_ersap_cpp_dpe.log: No such file or directory
=========================================
                 ERSAP DPE               
=========================================
 Name             = 10.0.2.100%7130_cpp
 Date             = 2023-01-28 02:40:52
 Version          = 4.3
 Lang             = C++

 Proxy Host       = 10.0.2.100
 Proxy Port       = 7130

 FrontEnd Host    = 10.0.2.100
 FrontEnd Port    = 7120
 FrontEnd Lang    = Java
=========================================
java.lang.IllegalStateException: config variable 'fileList' not set
        at org.jlab.epsci.ersap.std.cli.ConfigVariable.getValue(ConfigVariable.java:174)
        at org.jlab.epsci.ersap.std.cli.Config.getValue(Config.java:327)
        at org.jlab.epsci.ersap.std.cli.Config.getString(Config.java:341)
        at org.jlab.epsci.ersap.std.cli.RunCommand$RunLocal.orchestratorCmd(RunCommand.java:98)
        at org.jlab.epsci.ersap.std.cli.RunCommand$RunLocal.runOrchestrator(RunCommand.java:71)
        at org.jlab.epsci.ersap.std.cli.RunCommand$RunLocal.execute(RunCommand.java:55)
        at org.jlab.epsci.ersap.std.cli.BaseCommand.execute(BaseCommand.java:61)
        at org.jlab.epsci.ersap.std.cli.CommandRunner.execute(CommandRunner.java:55)
        at org.jlab.epsci.ersap.std.cli.ErsapShell.internalRun(ErsapShell.java:377)
        at java.base/java.lang.Thread.run(Thread.java:832)

```

### Usage
At the ersap-jana root repo:
```
docker build /docker/ubuntu_latest/

docker run -it -v ${PWD}:/app <docker_img_id_or_tag>
```

### CODE REVIEW

**Comment by cissieAB** [comment]
@nathanwbrei currently the Dockerfile locks to JANA v2.0.6, since if I do not lock to an older version and build ersap-jana, there would be a cmake error msg reads as below. I have no idea of that and ask for your help. Thanks very much!
```
# CMake Error at /deps/JANA2/install/lib/cmake/JANA/JANAConfig.cmake:31 (get_target_property):
#  get_target_property() called with non-existent target "JANA::jana2".
# Call Stack (most recent call first):
#  CMakeLists.txt:42 (find_package)
```

**Comment by cissieAB** [comment]
@gurjyan I have several questions for you:
1. I can build and install ersap-jana following the README, but I do not whether it's working or not. Can you hep me double check  the BUILT RESULTS part in the main post?
2. In the ersap-java dockerfile (https://github.com/JeffersonLab/ersap-java/blob/main/docker/Dockerfile), I see  `EXPOSE 7771-7775`. I copy them to the current Dockerfile. Are they still the right ports?
3. In the line below "Installation" (https://github.com/JeffersonLab/ersap-java#installation) in ersap-java README, there is a typo. The repo address is typed as "...githu**g**.com/..."
4. I wonder if you could add me into the ersap-jana repo since I have no permission here now.


Thanks so much for your help!

**Comment by cissieAB** [comment]
Built img can be found at https://hub.docker.com/layers/xxmei/ersap-jana/ubuntu/images/sha256-c93766907ee2f36e38503c489c4c71010cb1b4d89f2ee48be595258cd627d194?context=explore

**Comment by gurjyan** [comment]
@cissieAB 
The docker file in the repo needs to be updated (the old file that uses JDK 8). The current version of ersap-java uses JDK-14.
However, before containerizing, I suggest installing everything manually to see if things are working. A few configuration options, such as passing config parameters to the engine, need to be straightened out.
Monday, I will compile and install ersap-jana with its dependencies and will go from there.
BTW, you and Carl are added to the ersap-java repo as contributors.

**Pull request closed without merging**
